-- Таблица для управления правами доступа к страницам
CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id TEXT NOT NULL,
  page_id TEXT NOT NULL,
  allowed BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Уникальный ключ role_id + page_id
ALTER TABLE role_permissions ADD CONSTRAINT unique_role_page UNIQUE (role_id, page_id);

-- RLS
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

-- Политики - разрешаем всё для авторизованных пользователей
CREATE POLICY "Все могут читать" ON role_permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Все могут вставлять" ON role_permissions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Все могут обновлять" ON role_permissions FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Все могут удалять" ON role_permissions FOR DELETE TO authenticated USING (true);

-- Индекс
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions(role_id);