-- Add missing columns for Durak rooms
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS host_id TEXT;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS host_name TEXT;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'podkidnoy';
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS max_players INTEGER NOT NULL DEFAULT 2;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS timer_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS timer_seconds INTEGER NOT NULL DEFAULT 30;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS allow_bluff BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE durak_rooms ADD COLUMN IF NOT EXISTS auto_take BOOLEAN NOT NULL DEFAULT FALSE;